# Generated by Django 2.2.5 on 2022-02-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20211228_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='answer',
            field=models.CharField(max_length=5000),
        ),
    ]
