# Generated by Django 4.0.2 on 2022-02-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20220221_1509'),
        ('questions', '0004_auto_20220221_1510'),
    ]

    operations = [
    ]
